
package cs.calc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://server.calc.cs/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "last", targetNamespace = "http://server.calc.cs/", className = "cs.calc.client.Last")
    @ResponseWrapper(localName = "lastResponse", targetNamespace = "http://server.calc.cs/", className = "cs.calc.client.LastResponse")
    @Action(input = "http://server.calc.cs/Calculator/lastRequest", output = "http://server.calc.cs/Calculator/lastResponse")
    public int last();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://server.calc.cs/", className = "cs.calc.client.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://server.calc.cs/", className = "cs.calc.client.SumResponse")
    @Action(input = "http://server.calc.cs/Calculator/sumRequest", output = "http://server.calc.cs/Calculator/sumResponse")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://server.calc.cs/", className = "cs.calc.client.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://server.calc.cs/", className = "cs.calc.client.MulResponse")
    @Action(input = "http://server.calc.cs/Calculator/mulRequest", output = "http://server.calc.cs/Calculator/mulResponse")
    public int mul(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
